version: 1.4.{build}

branches:
  only:
  - master
  - dev

image: Visual Studio 2017

install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - ps: Vsix-TokenReplacement Kool.EditProject\Vsix.cs 'VERSION = "([0-9\\.]+)"' 'VERSION = "{version}"'

build_script:
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq 'dev') { Vsix-PushArtifacts }
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq 'master') { Vsix-PushArtifacts | Vsix-PublishToGallery }